#!/ bin/bash
gcc -S -Wall -Werror -Wextra -pedantic -std=gnu89  && c= && cat *.s > c
#!/bin/bash
gcc -S -Wall -Werror -Wextra -pedantic -std=gnu89  && c= && cat *.s > c
^#!\s*/bin/bash
gcc -S -Wall -Werror -Wextra -pedantic -std=gnu89  && c= && cat *.s > c
